name    'iouns-sysstat'
version '0.8.0'
source 'git://github.com/iouns/puppet-sysstat'
author 'iounes Gardon'
license 'GPLv3+'
summary 'Sysstat service configuration'
description 'Module to configure sysstat'
project_page 'https://github.com/Iouns/puppet-sysstat'
